export const FETCH_TV_SHOW_META = 'show/FETCH_TV_SHOW_META';
export const FETCH_TV_SHOW_PREV_EPISODE = 'show/FETCH_TV_SHOW_PREV_EPISODE';
export const FETCH_TV_SHOW_NEXT_EPISODE = 'show/FETCH_TV_SHOW_NEXT_EPISODE';
export const FETCH_TV_SHOW_SEASONS = 'show/FETCH_TV_SHOW_SEASONS';
